### ISSUE TITLE
Checkbox markdown code not consolidated

### ISSUE THREAD

**Issue by toneffectory** [Jeel-Shah/todo-wrangler#4]
Currently, lines starting with "TODO" or "- [] TODO" or "- TODO" will get consolidated.
However proper markdown code for a checkbox includes a whitespace between the brackets. But this is not consolidated.
Obsidian only renders a checkbox when done this way `- [ ]`. It will not render `- []` into a checkbox because of the missing whitespace.

So my question would be: would it be possible to add `- [ ] TODO` to the list of "to be consolidated TODO lines"?

**Comment by Jeel-Shah** [comment]
Hi @toneeffectory,

Sure, that sounds like a great idea. I will have it in the next release (< 2 weeks). If you would like, feel free to make a PR.
